name: Deploy PHP
run-name: Deploy PHP candidate by @${{ github.actor }}

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy PHP only
    uses: ./.github/workflows/_deploy-production-scope.yml
    with:
      release-scope: php
