name: Deploy Go services
run-name: Deploy Go services candidate by @${{ github.actor }}

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy selected Go services
    uses: ./.github/workflows/_deploy-production-scope.yml
    with:
      release-scope: go
