name: Deploy Node GC
run-name: Deploy Node GC candidate by @${{ github.actor }}

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy Node GC only
    uses: ./.github/workflows/_deploy-production-scope.yml
    with:
      release-scope: node
